---
title: ""
description: Documentation on various topics
url: https://giftpilz0.github.io
baseurl: /

plugins:
  - jekyll-seo-tag
  - jekyll-include-cache

# Theme
theme: just-the-docs
color_scheme: material-dark
favicon_ico: /assets/images/favicon.svg
logo: /assets/images/favicon.svg

# Misc
nav_fold: true
search_enabled: true
heading_anchors: true
enable_copy_code_button: true
last_edit_timestamp: false
nav_sort: case_sensitive

# Footer
gh_edit_link: true
gh_edit_branch: main
gh_edit_view_mode: tree
gh_edit_repository: https://github.com/giftpilz0/giftpilz0.github.io
gh_edit_link_text: Edit this page on GitHub.

# Diagrams
mermaid:
  version: 10.6.1

# Collections
collections:
  projectdocs:
    permalink: /:collection/:path/
    output: true

just_the_docs:
  collections:
    projectdocs:
      name: project documetation
      nav_fold: true

# Aux links for the upper right navigation
aux_links:
  View on GitHub:
    - //github.com/giftpilz0/giftpilz0.github.io

# Callout boxes
callouts_level: loud
callouts:
  note:
    title: Note
    color: yellow

# Jekyll excludes
exclude:
  - Gemfile
  - Gemfile.lock
  - .jekyll-cache/
