title: Dokumentation
theme: just-the-docs
baseurl: ""
url: "https://giftpilz0.github.io"

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

search_enabled: true
color_scheme: overridedark

ga_tracking:
ga_tracking_anonymize_ip:

mermaid:
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.3.0"

callouts:
  highlight:
    color: yellow
    opacity: 0.3
  important:
    title: Important
    color: blue
    opacity: 0.3
  new:
    title: New
    color: green
    opacity: 0.3
  note:
    title: Note
    color: pink
    opacity: 0.3
  warning:
    title: Warning
    color: red
    opacity: 0.3
