title: Documentation
description: Documentation on various topics
baseurl: /
url: "https://giftpilz0.github.io"

# Theme
theme: just-the-docs
color_scheme: nord-dark
favicon_ico: ""

# Search
search_enabled: true

# Diagrams
mermaid:
  version: "9.3.0"

# Aux links for the upper right navigation
aux_links:
  "View on GitHub":
    - "https://github.com/giftpilz0/giftpilz0.github.io"

# Sort order for navigation links
nav_sort: case_sensitive

# Callout boxes
callouts_level: loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

# Codeblocks
enable_copy_code_button: true

# Jekyll excludes
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - .jekyll-cache/
