import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  toolsSidebar: [{ type: "autogenerated", dirName: "docs" }],
  projectSidebar: [{ type: "autogenerated", dirName: "projects" }],
};

export default sidebars;
